app.py
from flask import Flask, render_template,  session
from flask_session import Session
from views import views
from auth import auth
from datetime import timedelta

app = Flask(__name__)
app.config['FLASK_ENV'] = 'development'
app.config['SECRET_KEY'] = "INFSCI2150_crackpassword"
app.config['SESSION_TYPE'] = 'filesystem'
app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(minutes=50)

app.register_blueprint(views, url_prefix='/')
app.register_blueprint(auth, url_prefix='/')


"""Run App"""
if __name__ == "__main__":
    app.run(debug=True)

auth.py
import hashlib
import re
from config import auth_list
from config import auth_details
from flask import Flask, render_template, request, Blueprint, session, redirect, url_for, flash
from flask_session import Session
from password_cracker import crack_pwd
auth = Blueprint('auth', __name__)


@auth.route('/index', methods=['GET', 'POST'])
def index():
    if session.get("user_name"):
        return redirect(url_for('auth.get_details'))
    return render_template("index.html", authenticated=False)

@auth.route('/sign_up', methods=['GET', 'POST'])
def sign_up():
    if request.method == "POST":
        error_msg = ''
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        user_name = request.form.get('user_name').lower()
        email = request.form.get('email')
        password = request.form.get('psw')
        password_conf = request.form.get('psw-repeat')
        with open(auth_list) as f:
            for line in f:
                if line.split("\t")[0] == user_name:
                    flash('Account already exists with this user name!! Please Login or choose another username')
                    return redirect(url_for('auth.sign_up'))
        match = re.search(r'[A-Z]+', password)
        num_numbers = len(re.findall('\d', password))
        if count_special_char(password) > 2 or num_numbers > 2 or match:
            error_msg += "Passwords must contain only lowercase letters with max two digits repetition amd max two special characters ('@', '#', '$', '%', '&') with no repetition"
        if password != password_conf:
            error_msg += 'Passwords do not match'
        if error_msg:
            flash(error_msg)
            return redirect(url_for('auth.sign_up'))
        else:
            hash_pwd = hashlib.md5(password.encode()).hexdigest()
            fl = open(auth_list, "a+")
            fl.write(user_name + "\t" + str(hash_pwd) + "\n")
            fl.close()

            fd = open(auth_details, "a+")
            fd.write(user_name + "\t" + first_name + "\t" + last_name + "\t" + email + "\n")
            fd.close()
            return redirect(url_for('auth.login'))
    return render_template("sign_up.html", title="Sign Up", authenticated=False)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        user_name = request.form.get('user_name').lower()
        password = request.form.get('psw')
        hash_pwd = hashlib.md5(password.encode()).hexdigest()
        user_found = False
        with open(auth_list) as f:
            for line in f:
                if line.split("\t")[0] == user_name:
                    user_found = True
                    if line.split("\t")[1].strip() != str(hash_pwd):
                        flash('Invalid Login Credentials!!')
                        return redirect(url_for('auth.login'))
        if not user_found:
            flash('Invalid Login Credentials!!')
            return redirect(url_for('auth.sign_up'))
        session["user_name"] = user_name
        return redirect(url_for('auth.get_details'))
    return render_template("login.html", title="Login", authenticated=False)

@auth.route("/get_details")
def get_details():
    if not session.get("user_name"):
        return redirect(url_for("auth.index"))
    user_name = session["user_name"]
    with open(auth_details) as f:
        for line in f:
            details = line.split("\t")
            if details[0] == user_name:
                session["user_name"] = user_name
                return render_template("home.html", title="User Details", authenticated=True, first_name=details[1], last_name=details[2],
                                       user_name=details[0], email=details[3])


@auth.route("/logout")
def logout():
    session["user_name"] = None
    return redirect(url_for("auth.index"))

@auth.route('/crack_password', methods=['GET', 'POST'])
def crack_password():
    authenticated = True
    if not session.get("user_name"):
        authenticated = False
    if request.method == "POST":
        user_name = request.form.get('user_name').lower()
        password = ""
        password_strength = ""
        time_taken = ""
        detailed = request.form.get('detailed') == 'detailed'
        pwd_details = crack_pwd(user_name, detailed)
        if pwd_details[0]:
            msg = "Password cracked Successfully!!"
            password = pwd_details[1]
            password_strength = pwd_details[2]
            time_taken = pwd_details[3]
        else:
            if len(pwd_details) == 5 and len(pwd_details[4]) > 0:
                msg = "Account not found with username "+user_name+"!!"
            else:
                msg = "Unable to crack Password!!"
        return render_template("crack_password.html", title="Password Details of User", cracked=pwd_details[0], user_name=user_name, password=password, password_strength=password_strength, time_taken=time_taken, msg=msg, authenticated=authenticated)
    return render_template("crack_password.html", title="Crack Password",authenticated=authenticated)

@auth.route('/validate_password', methods=['GET', 'POST'])
def validate_password():
    if not session.get("user_name"):
        flash("Either Sign up or Login to validate password")
        return redirect(url_for("auth.index"))
    user_name = session["user_name"]
    with open(auth_details) as f:
        for line in f:
            details = line.split("\t")
            if details[0] == user_name:
                pwd_details = crack_pwd(user_name)
                password_strength = pwd_details[2]
                time_taken = pwd_details[3]
                return render_template("validate_password.html", title="Password Validation Details of User", validated="True", authenticated=True, first_name=details[1], last_name=details[2],
                                       user_name=details[0], email=details[3], cracked=pwd_details[0], password_strength=password_strength, time_taken=time_taken)


def count_special_char(s):
    n = 0
    for c in s:
        if not (c.isalpha() or c.isdigit() or c == ' '):
            n += 1
    return n

views.py
from flask import Flask, render_template, request, flash, Blueprint
views = Blueprint('views', __name__)

@views.route('/')
def index():
    return render_template("index.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Information Security & Privacy: {{title}}</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='index.css')}}">
    {% block head %}
    {% endblock %}
</head>
<body>

<div class="header">
  <h1>Information Security & Privacy</h1>
</div>

<div class="topnav">
  <div class="search-container">
      {% if authenticated %}
      <a href="{{ url_for('auth.validate_password') }}">Validate My Password</a>
      <a href="{{ url_for('auth.logout') }}">Logout</a>
      {% else %}
      <a href="{{ url_for('auth.sign_up') }}">Sign Up</a>
      <a href="{{ url_for('auth.login') }}">Login</a>
      {% endif %}
      <a href="{{ url_for('auth.crack_password') }}">Crack Password</a>
  </div>
</div>

{% for error in error_msgs %}
<span style="color:red;">{{error}}</span><br/>
{% endfor %}

{% for msg in get_flashed_messages() %}
      <span style="color:red;">{{msg}}</span><br/>
{% endfor %}

{% block content %}
{% endblock %}

</body>
</html>

templates/content.html
<div class="row">
    <div class="column side">
    </div>
    <div class="column middle">
      <p>In today's digital age, where personal information is increasingly shared and stored online, ensuring information security and privacy has become more important than ever. The vast amount of data collected and processed by individuals, organizations, and governments raises concerns about the protection of sensitive information and the potential for unauthorized access or misuse.</p>
      <p>Information security refers to the measures and practices implemented to safeguard information from unauthorized access, use, disclosure, disruption, modification, or destruction. It encompasses a range of technologies, processes, and policies designed to protect data from threats such as hacking, data breaches, malware, and social engineering attacks.</p>
      <p>Privacy, on the other hand, focuses on individuals' control over their personal information and the right to keep it confidential. Privacy involves protecting personal data from unauthorized collection, use, or disclosure by organizations or individuals. It also encompasses the ability to make informed choices about the sharing and use of personal information.</p>
      <p>Both information security and privacy are closely intertwined and form the foundation of trust in the digital ecosystem. </p>
      <p>Here are some key aspects to consider:</p>
      <ul>
          <li><u>Confidentiality:</u> Information should be accessible only to authorized individuals or entities. Encryption, access controls, and secure communication channels are essential to maintaining confidentiality.</li>
          <li><u>Integrity:</u> Information should be accurate, complete, and unaltered during storage, processing, and transmission. Data integrity measures, such as data validation and error checking, help ensure the reliability and trustworthiness of information.</li>
          <li><u>Availability:</u> Information should be available to authorized users when needed. This involves implementing backup and disaster recovery plans, maintaining system uptime, and protecting against denial-of-service attacks.</li>
          <li><u>Authentication and Authorization:</u> Strong authentication mechanisms, such as passwords, biometrics, or multi-factor authentication, verify the identity of users. Authorization controls determine the level of access granted to individuals based on their roles and responsibilities.</li>
          <li><u>Data Protection:</u> Adequate safeguards must be in place to protect personal and sensitive data from unauthorized access or disclosure. This includes secure data storage, data anonymization or pseudonymization, and compliance with privacy regulations.</li>
          <li><u>Security Awareness and Training:</u> Education and training programs help individuals understand their role in maintaining information security and privacy. By promoting good security practices, organizations can reduce the risk of human error and enhance overall security posture.</li>
          <li><u>Compliance and Regulations:</u> Organizations must adhere to relevant laws, regulations, and industry standards pertaining to information security and privacy. This includes data protection regulations like the General Data Protection Regulation (GDPR) or the California Consumer Privacy Act (CCPA).</li>
          <li><u>Incident Response and Recovery:</u> Preparedness for security incidents is crucial. Organizations should have incident response plans in place to detect, respond to, and recover from security breaches or privacy incidents promptly.</li>
      </ul>
      <p>Ensuring information security and privacy requires a holistic approach involving technical measures, organizational policies, and user awareness. By prioritizing these aspects, we can create a safer digital environment and protect individuals' personal information from unauthorized access or misuse.</p>
    </div>
</div>

templates/crack_password.html
{% extends 'base.html' %}
{% block head %}
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for all buttons */
button {
  background-color: black;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Extra styles for the cancel button */
.cancelbtn {
  padding: 14px 20px;
  background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}

/* Add padding to container elements */
.container {
  padding: 16px;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .signupbtn {
     width: 100%;
  }
}
</style>

{% endblock %}
{% block content %}
<form method="POST" action="crack_password" style="border:1px solid #ccc">
    <div class="container">
        <h1>Crack Password</h1>
        <p>Please fill in user details.</p>
        <hr>
        <label for="user_name"><b>User Name</b></label>
        <input type="text" placeholder="Enter User Name" name="user_name" id="user_name" required>
        {% if authenticated %}
        <label for="detailed"><b>In Detail?</b></label>
        <input type="checkbox" name="detailed" id="detailed" value="detailed">
        <p><small>To check all possible passwords (in between the string)</small></p>
        {% endif %}
        <div class="clearfix">
            <button type="submit" class="signupbtn">Submit</button>
        </div>
  </div>
</form>

{% if msg %}
    <p>{{msg}}</p>
    <p><b>Details</b></p>
    <table>
        <tr>
            <td>User Name:</td>
            <td>{{user_name}}</td>
        </tr>
        <tr>
            <td>Password:</td>
            <td>{{password}}</td>
        </tr>
        <tr>
            <td>Time Taken:</td>
            <td>{{time_taken}}</td>
        </tr>
    </table>
{% endif %}

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="column side">
    </div>
    <div class="column middle">
        Welcome!! Nice Meeting you {{last_name}}, {{first_name}}!
        <p><b>Auth Details</b></p>
        <table>
            <tr>
                <td>First Name:</td>
                <td>{{first_name}}</td>
            </tr>
            <tr>
                <td>Last Name:</td>
                <td>{{last_name}}</td>
            </tr>
            <tr>
                <td>User Name:</td>
                <td>{{user_name}}</td>
                </tr>
            <tr>
                <td>Email</td>
                <td>{{email}}</td>
            </tr>
        </table>
    </div>
</div>
{% include "content.html" %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
{% include "content.html" %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}
  {% block head %}
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for all buttons */
button {
  background-color: black;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Extra styles for the cancel button */
.cancelbtn {
  padding: 14px 20px;
  background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}

/* Add padding to container elements */
.container {
  padding: 16px;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .signupbtn {
     width: 100%;
  }
}
</style>
{% endblock %}
{% block content %}

<form method="POST" style="border:1px solid #ccc">
  <div class="container">
    <h1>Login</h1>
    <p>Please fill in this form to login.</p>
    <hr>

    <label for="user_name"><b>User Name</b></label>
    <input type="text" placeholder="Enter User Name" name="user_name" id="user_name" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" id="psw" required>

    <div class="clearfix">
      <button type="submit" class="signupbtn">Login</button>
    </div>
  </div>
</form>
{% endblock %}

templates/sign_up.html
{% extends 'base.html' %}
  {% block head %}
  <style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for all buttons */
button {
  background-color: black;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Extra styles for the cancel button */
.cancelbtn {
  padding: 14px 20px;
  background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}

/* Add padding to container elements */
.container {
  padding: 16px;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .signupbtn {
     width: 100%;
  }
}
</style>
{% endblock %}
{% block content %}
<form method="POST" style="border:1px solid #ccc">
  <div class="container">
    <h1>Sign Up</h1>
    <p>Please fill in this form to create an account.</p>
    <hr>
    <label for="first_name"><b>First Name</b></label>
    <input type="text" placeholder="Enter First Name" name="first_name" id="first_name" value="{{ request.form['first_name'] }}" required>

    <label for="last_name"><b>Last Name</b></label>
    <input type="text" placeholder="Enter Last Name" name="last_name" id="last_name" value="{{ request.form['last_name'] }}" required>

    <label for="user_name"><b>User Name</b></label>
    <input type="text" placeholder="Enter User Name" name="user_name" id="user_name" value="{{ request.form['user_name'] }}" title="Username is not case sensitive" required>

    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" id="email" value="{{ request.form['email'] }}" required>

    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" id="psw" pattern="^[a-z0-9@#$%&]+$" required title="only lowercase with max two digits with no repetition amd max two special characters ('@', '#', '$', '%', '&') with no repetition">

    <label for="psw-repeat"><b>Repeat Password</b></label>
    <input type="password" placeholder="Repeat Password" name="psw-repeat" id="psw-repeat" required>

    <div class="clearfix">
      <button type="submit" class="signupbtn">Sign Up</button>
    </div>
  </div>
</form>
{% endblock %}

templates/validate_password.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="column side">
    </div>
    <div class="column middle">
        Welcome!! Nice Meeting you {{last_name}}, {{first_name}}!
        <p><b>Auth Details</b></p>
        <table>
            <tr>
                <td>First Name:</td>
                <td>{{first_name}}</td>
            </tr>
            <tr>
                <td>Last Name:</td>
                <td>{{last_name}}</td>
            </tr>
            <tr>
                <td>User Name:</td>
                <td>{{user_name}}</td>
                </tr>
            <tr>
                <td>Email</td>
                <td>{{email}}</td>
            </tr>
        </table>
        {% if validated %}
        <p><b>Password Details</b></p>
        <table>
            <tr>
                <td>Password Strength:</td>
                <td>{{password_strength}}</td>
            </tr>
            <tr>
                <td>Password Cracked:</td>
                <td>{{cracked}}</td>
            </tr>
            {% if cracked %}
                <tr>
                    <td>Time Taken</td>
                    <td>{{time_taken}}</td>
                </tr>
            {% endif %}
        </table>
        {% endif %}
    </div>
</div>
{% include "content.html" %}
{% endblock %}